### Zwraca listę ButyDTO (id, nazwa...)
GET http://localhost:8090/api/buty

### Zwraca listę NartyDTO (id, nazwa...)
GET http://localhost:8090/api/narty

### Posiadamy id butów i id nart
POST http://localhost:8090/api/komplet
Content-Type: application/json


### Posiadamy id butów i id nart
GET http://localhost:8090/api/klient


### Posiadamy id butów i id nart
GET http://localhost:8090/api/komplet

### Posiadamy id butów i id nart
POST http://localhost:8090/api/wypozyczenie/rent
Content-Type: application/json

{
  "idWypozyczenie": 4

}


